version: "3"
services:
  mysql:
    image: avzeus-mysql_dev:1.0
    ports:
      - "3306:3306"

  backend:
    image: avzeus-backend_dev:1.0
    depends_on:
      - mysql
    ports:
      - "8000:8000"
